class CartLocators:
    DELIVERIES_ITEMS_BLOCK = "#basket-items-list-wrapper"
    RADIO_BTN_COURIER_MINSK = "[data-id='48']"
    CART_STREET_INPUT = "[name='ORDER_PROP_22']"
    STREET_LABEL_CART = "label:has-text('Улица')"
    STREET_MAP_CART = "[class *= 'search__suggest-item']"
    HOUSE_INPUT_CART = "[placeholder='Введите дом']"
    MINSK_DATE_FIELD = "[class *= 'date-input']"
    MINSK_CHOOSE_DATE = "[class='bx-calendar-cell']"
    TO_CHECKOUT_BTN = "#ga__cart__checkout"
    CART_AUTH_BTN = ".authorize-block_link"
    COMMENT_FIELD = "#customComment"
    CHECK_COMMENT = "#orderDescription"
    NOT_VALID_FIELD_INPUT = ".bad-field-check"
    TO_PLACE_ORDER_BTN = "#ga__cart__confirm_order"
    ORDER_CREATED_SUCCESSFULLY_POPUP = ".thanks"
    ORDER_INFO_BLOCK_IN_SUCCESSFUL_POPUP = ".order-info"
    CLOSE_SUCCESSFUL_POPUP_BTN = ".mfp-close"
    RADIO_BTN_PICKUP_CART = "[data-id='52']"
    CHOOSE_PICKUP_STORE_CART = ".chose-point"
    RADIO_BTN_BY_POST = "[data-id='4']"
    POSTCODE_INPUT_CART = "[placeholder='Введите индекс']"
    PAY_BY_CARD_IN_CART = "[data-id='9']"
    ASSIST_PAGE_LOGO = "[data-tdata='[src]page.style.logo']"
