class HeaderLocators:
    INFOLINE = ".app-header__top-text"
    INFOLINE_CLOSE = ".app-header_close-button"
    CATALOG = ".app-header-btn.app-hamburger-btn:has-text('Каталог')"
    OPEN_ALL_FOR_WOMEN = "li.daughter.depth_2 > a[href='/catalog/zhenshchinam/']"
    STORES_HEADER = ".app-header-btn:has-text('Магазины')"
    LOCATION_HEADER = ".app-header__select-city-btn"
    LOGO = ".logo-desktop"
    SEARCH = ".search-lupa-btn"
    SEARCH_FIELD = "#header-search-input"
    SEARCH_CLOSE = ".search-cross-btn"
    SEARCH_SUBMIT_BTN = ".search-lupa-fake"
    SEARCH_POPULAR = ".app-desktop-search__popup-link"
    PROFILE_HEADER = ".js-profile-open"
    FAVORITES = "#ico-favorites"
    CART_HEADER = "a[data-basket$='/personal/cart/']"
    AUTH_POPUP_LOG_IN_WITH_LOGIN = ".alternative-auth-link"
    AUTH_POPUP_LOGIN_FIELD = "[name=USER_LOGIN]"
    AUTH_POPUP_PWD_FIELD = "[name=USER_PASSWORD]"
    AUTH_POPUP_SUBMIT_LOGIN_PWD = ".registration-button.mail-submit-button"
    USER_IS_LOGED_IN = "[class='app-header__navbar-link app-desktop-visible js-profile-open']"
    FOR_MEN_CATALOG_TAB = "#fake-menu-2"
    OPEN_ALL_FOR_MEN = "li.daughter.depth_2 > a[href='/catalog/muzhchinam/']"
